### PR TITLE
Homework22 tests

### PR DESCRIPTION
**Pull request by ochaklosh**
Updated LoginTests.java by updating all of the tests with POM

### CODE REVIEW

**Comment by Berichicko** [comment]
**General recommendations:**


Please, use **Encapsulation**

Encapsulation is one of the four fundamental OOP concepts. The other three are inheritance, polymorphism, and abstraction.

You should use encapsulation of non-static and non-final fields.

If a variable is used only by other methods of that class, it should be declared as private.

Make all the locators and WebElements private, because private keyword in java allows most restrictive access to variables and methods and offer strongest form of Encapsulation. 

For example
```
private By shuffleBtnLocator = By.cssSelector(".btn-shuffle-all");
private By firstSongLocator = By.cssSelector(".play");
```



Make the variables protected, because protected access gives the subclass a chance to use the helper method or variable, while preventing a nonrelated class from trying to use it.

```
    protected Actions actions;
    protected WebDriverWait wait;
    protected WebDriver driver;
```

**Comment by ochaklosh** [comment]
Thanks.
This was not even mentioned in the examples of this code in LMS.
Just updated the code encapsulating the variables.

________________________________

**Comment by Berichicko** [comment]
Hi dear Oksana

You got this problem, please correct it.

image

image

**HINT**

**Step 1**

**Use these methods in the BasePage, and then in child classes**

```
package pages;

import java.util.List;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.TimeoutException;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;


import java.time.Duration;

public class BasePage {

    protected WebDriver driver;
    protected WebDriverWait wait;
    protected Actions actions;



    public BasePage(WebDriver givenDriver){
        driver = givenDriver;
        wait = new WebDriverWait(driver, Duration.ofSeconds(10));
        actions = new Actions(driver);
    }

    public WebElement findElementVisibility(By locator){
        return wait.until(ExpectedConditions.visibilityOfElementLocated(locator));
    }
    public WebElement findElementAndClickability(By locator){
          return wait.until(ExpectedConditions.elementToBeClickable(locator));
        }

    public void click(By locator){
        findElementAndClickability(locator).click();
    }

    public void doubleClick(By locator){
        actions.doubleClick(findElementVisibility(locator)).perform();
    }

    // Method to wait for an element to be present on the page
    public WebElement waitForPresence(By by) {
        return wait.until(ExpectedConditions.presenceOfElementLocated(by));
    }

    // Method to wait for all elements to be present on the page
    public List<WebElement> waitForPresenceOfAllElements(By by) {
        return wait.until(ExpectedConditions.presenceOfAllElementsLocatedBy(by));
    }

    // Method to wait for an element to be visible on the page
    public WebElement waitForVisibility(By by) {
        return wait.until(ExpectedConditions.visibilityOfElementLocated(by));
    }

    // Method to wait until all elements are visible on the page
    public List<WebElement> waitUntilAllElementsLocatedByAreVisible(By by) {
        return wait.until(ExpectedConditions.visibilityOfAllElementsLocatedBy(by));
    }

    // Method to wait until all required elements are invisible
    public boolean waitUntilRequiredElementsAreInvisible(List<WebElement> elements) {
        return wait.until(ExpectedConditions.invisibilityOfAllElements(elements));
    }



     // Method to click an element after waiting for it to be visible
    public void tryClick(By by) {
        waitForVisibility(by).click();
    }

    // Method to click an element without any wait
    public void tryClickNoWait(By by) {
        driver.findElement(by).click();
    }

    // Method to move the mouse over an element and click it
    public void mouseOverAndJavascriptExecutorClick(By by) {
        try {
            WebElement element = wait.until(ExpectedConditions.visibilityOfElementLocated(by));
            actions.moveToElement(element).perform();
            actions.click(element).build().perform();
        } catch (TimeoutException e) {
            System.out.println("Standard click failed, trying JavaScript click");
            WebElement element = driver.findElement(by);
            String mouseOverScript = "var event = new MouseEvent('mouseover', { 'view': window, 'bubbles': true, 'cancelable': true }); arguments[0].dispatchEvent(event);";
            ((JavascriptExecutor) driver).executeScript(mouseOverScript, element);
            ((JavascriptExecutor) driver).executeScript("arguments[0].click();", element);
        }
    }

    // Method to move the mouse over an element and click and hold it
    public void mouseOverAndClickAndHold(By by) {
        WebElement element = driver.findElement(by);
        actions.moveToElement(element).clickAndHold().perform();
    }

}
```

**Step 2**

image


```
package pages;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;

public class HomePage extends BasePage {

  //LOCATORS
  private final By userAvatarIcon = By.cssSelector("img.avatar");
  private final By allSongsList = By.cssSelector("li a.song");
  private final By playBtn = By.xpath("//footer[@id='mainFooter']//span[@class='play']//i");
  private final By soundBar = By.xpath("//img[@alt='Sound bars']");
  //CONSTRUCTOR
  public HomePage(WebDriver givenDriver) {
    super(givenDriver);
  }

  //METHODS
  public WebElement getUserAvatar() {
    return findElementVisibility(userAvatarIcon);
  }

  public void chooseAllSongsList() {
    findElementAndClickability(allSongsList).click();
  }

  public void playButtonSong() {
    mouseOverAndJavascriptExecutorClick(playBtn);
  }

  public boolean isDisplayedPlaingSong() {
    return findElementVisibility(soundBar).isDisplayed();
  }
}
```

**Step 3**

**Use in test methods, the following logical split:   GIVEN – WHEN - THEN**

image

image

**Information:** if your problem is still not solved, you need a DOM-level solution. So, we need an interface that helps to execute JavaScript with Selenium WebDriver. It is called JavaScriptExecutor. JavaScript works at the DOM level. Therefore, we are able to click any web element by using JavaScript executor.

**Clicking Elements in Selenium using JavaScript** (https://www.baeldung.com/java-selenium-javascript)

**Comment by Berichicko** [comment]
Hi dear Oksana

image


HINT

When testing, it's better to store how you find **elements on a webpage in class variables or separate files/classes.** This keeps your code organized and makes updates easier, so you don't have to change every method where you use those elements. It helps make your code clearer and reduces mistakes.

For example

image

We can make the xpath or css the class variable (Locator)

Screenshot_9

**Pull request merged**
